all:
	@cd `find . -name "*helloworld*"`; make -f Makefile.build release
	@cd `find . -name "*hellogl2*"`; make -f Makefile.build release
	@cd `find . -name "*digiflip*"`; make -f Makefile.build release
clean:
	@cd `find . -name "*helloworld*"`; make -f Makefile.build clean
	@cd `find . -name "*hellogl2*"`; make -f Makefile.build clean
	@cd `find . -name "*digiflip*"`; make -f Makefile.build clean
