/*
 *  Copyright 2017 by Texas Instruments Incorporated.
 *
 */

/* this file was generated by xdc/bld/stddefs.xdt */
/*
 *  @(#) gnu.targets; 1, 0, 1,1; 7-27-2017 11:46:50; /db/ztree/library/trees/xdctargets/xdctargets-o04/src/ xlibrary

 */

