/*
 *  Do not modify this file; it is automatically 
 *  generated and any modifications will be overwritten.
 *
 * @(#) xdc-D20
 */

#ifndef ti_sdo_ipc_family_vayu_NotifyDriverMbx__INTERNAL__
#define ti_sdo_ipc_family_vayu_NotifyDriverMbx__INTERNAL__

#ifndef ti_sdo_ipc_family_vayu_NotifyDriverMbx__internalaccess
#define ti_sdo_ipc_family_vayu_NotifyDriverMbx__internalaccess
#endif

#include <ti/sdo/ipc/family/vayu/NotifyDriverMbx.h>

#undef xdc_FILE__
#ifndef xdc_FILE
#define xdc_FILE__ NULL
#else
#define xdc_FILE__ xdc_FILE
#endif

/* registerEvent */
#undef ti_sdo_ipc_family_vayu_NotifyDriverMbx_registerEvent
#define ti_sdo_ipc_family_vayu_NotifyDriverMbx_registerEvent ti_sdo_ipc_family_vayu_NotifyDriverMbx_registerEvent__E

/* unregisterEvent */
#undef ti_sdo_ipc_family_vayu_NotifyDriverMbx_unregisterEvent
#define ti_sdo_ipc_family_vayu_NotifyDriverMbx_unregisterEvent ti_sdo_ipc_family_vayu_NotifyDriverMbx_unregisterEvent__E

/* sendEvent */
#undef ti_sdo_ipc_family_vayu_NotifyDriverMbx_sendEvent
#define ti_sdo_ipc_family_vayu_NotifyDriverMbx_sendEvent ti_sdo_ipc_family_vayu_NotifyDriverMbx_sendEvent__E

/* disable */
#undef ti_sdo_ipc_family_vayu_NotifyDriverMbx_disable
#define ti_sdo_ipc_family_vayu_NotifyDriverMbx_disable ti_sdo_ipc_family_vayu_NotifyDriverMbx_disable__E

/* enable */
#undef ti_sdo_ipc_family_vayu_NotifyDriverMbx_enable
#define ti_sdo_ipc_family_vayu_NotifyDriverMbx_enable ti_sdo_ipc_family_vayu_NotifyDriverMbx_enable__E

/* disableEvent */
#undef ti_sdo_ipc_family_vayu_NotifyDriverMbx_disableEvent
#define ti_sdo_ipc_family_vayu_NotifyDriverMbx_disableEvent ti_sdo_ipc_family_vayu_NotifyDriverMbx_disableEvent__E

/* enableEvent */
#undef ti_sdo_ipc_family_vayu_NotifyDriverMbx_enableEvent
#define ti_sdo_ipc_family_vayu_NotifyDriverMbx_enableEvent ti_sdo_ipc_family_vayu_NotifyDriverMbx_enableEvent__E

/* setNotifyHandle */
#undef ti_sdo_ipc_family_vayu_NotifyDriverMbx_setNotifyHandle
#define ti_sdo_ipc_family_vayu_NotifyDriverMbx_setNotifyHandle ti_sdo_ipc_family_vayu_NotifyDriverMbx_setNotifyHandle__E

/* isr */
#define NotifyDriverMbx_isr ti_sdo_ipc_family_vayu_NotifyDriverMbx_isr__I

/* Module_startup */
#undef ti_sdo_ipc_family_vayu_NotifyDriverMbx_Module_startup
#define ti_sdo_ipc_family_vayu_NotifyDriverMbx_Module_startup ti_sdo_ipc_family_vayu_NotifyDriverMbx_Module_startup__E

/* Instance_init */
#undef ti_sdo_ipc_family_vayu_NotifyDriverMbx_Instance_init
#define ti_sdo_ipc_family_vayu_NotifyDriverMbx_Instance_init ti_sdo_ipc_family_vayu_NotifyDriverMbx_Instance_init__E

/* Instance_finalize */
#undef ti_sdo_ipc_family_vayu_NotifyDriverMbx_Instance_finalize
#define ti_sdo_ipc_family_vayu_NotifyDriverMbx_Instance_finalize ti_sdo_ipc_family_vayu_NotifyDriverMbx_Instance_finalize__E

/* module */
#ifdef ti_sdo_ipc_family_vayu_NotifyDriverMbx_Module__state__VR
#define NotifyDriverMbx_module ((ti_sdo_ipc_family_vayu_NotifyDriverMbx_Module_State *)(xdcRomStatePtr + ti_sdo_ipc_family_vayu_NotifyDriverMbx_Module__state__V_offset))
#define module ((ti_sdo_ipc_family_vayu_NotifyDriverMbx_Module_State *)(xdcRomStatePtr + ti_sdo_ipc_family_vayu_NotifyDriverMbx_Module__state__V_offset))
#else
#define NotifyDriverMbx_module ((ti_sdo_ipc_family_vayu_NotifyDriverMbx_Module_State *)(xdc__MODOBJADDR__(ti_sdo_ipc_family_vayu_NotifyDriverMbx_Module__state__V)))
#if !defined(__cplusplus) ||!defined(ti_sdo_ipc_family_vayu_NotifyDriverMbx__cplusplus)
#define module ((ti_sdo_ipc_family_vayu_NotifyDriverMbx_Module_State *)(xdc__MODOBJADDR__(ti_sdo_ipc_family_vayu_NotifyDriverMbx_Module__state__V)))
#endif
#endif

/* per-module runtime symbols */
#undef Module__MID
#ifdef ti_sdo_ipc_family_vayu_NotifyDriverMbx_Module__id__CR
#define Module__MID (*((CT__ti_sdo_ipc_family_vayu_NotifyDriverMbx_Module__id *)(xdcRomConstPtr + ti_sdo_ipc_family_vayu_NotifyDriverMbx_Module__id__C_offset)))
#else
#define Module__MID ti_sdo_ipc_family_vayu_NotifyDriverMbx_Module__id__C
#endif

#undef Module__DGSINCL
#ifdef ti_sdo_ipc_family_vayu_NotifyDriverMbx_Module__diagsIncluded__CR
#define Module__DGSINCL (*((CT__ti_sdo_ipc_family_vayu_NotifyDriverMbx_Module__diagsIncluded *)(xdcRomConstPtr + ti_sdo_ipc_family_vayu_NotifyDriverMbx_Module__diagsIncluded__C_offset)))
#else
#define Module__DGSINCL ti_sdo_ipc_family_vayu_NotifyDriverMbx_Module__diagsIncluded__C
#endif

#undef Module__DGSENAB
#ifdef ti_sdo_ipc_family_vayu_NotifyDriverMbx_Module__diagsEnabled__CR
#define Module__DGSENAB (*((CT__ti_sdo_ipc_family_vayu_NotifyDriverMbx_Module__diagsEnabled *)(xdcRomConstPtr + ti_sdo_ipc_family_vayu_NotifyDriverMbx_Module__diagsEnabled__C_offset)))
#else
#define Module__DGSENAB ti_sdo_ipc_family_vayu_NotifyDriverMbx_Module__diagsEnabled__C
#endif

#undef Module__DGSMASK
#ifdef ti_sdo_ipc_family_vayu_NotifyDriverMbx_Module__diagsMask__CR
#define Module__DGSMASK (*((CT__ti_sdo_ipc_family_vayu_NotifyDriverMbx_Module__diagsMask *)(xdcRomConstPtr + ti_sdo_ipc_family_vayu_NotifyDriverMbx_Module__diagsMask__C_offset)))
#else
#define Module__DGSMASK ti_sdo_ipc_family_vayu_NotifyDriverMbx_Module__diagsMask__C
#endif

#undef Module__LOGDEF
#ifdef ti_sdo_ipc_family_vayu_NotifyDriverMbx_Module__loggerDefined__CR
#define Module__LOGDEF (*((CT__ti_sdo_ipc_family_vayu_NotifyDriverMbx_Module__loggerDefined *)(xdcRomConstPtr + ti_sdo_ipc_family_vayu_NotifyDriverMbx_Module__loggerDefined__C_offset)))
#else
#define Module__LOGDEF ti_sdo_ipc_family_vayu_NotifyDriverMbx_Module__loggerDefined__C
#endif

#undef Module__LOGOBJ
#ifdef ti_sdo_ipc_family_vayu_NotifyDriverMbx_Module__loggerObj__CR
#define Module__LOGOBJ ti_sdo_ipc_family_vayu_NotifyDriverMbx_Module__loggerObj__R
#define Module__LOGOBJ (*((CT__ti_sdo_ipc_family_vayu_NotifyDriverMbx_Module__loggerObj *)(xdcRomConstPtr + ti_sdo_ipc_family_vayu_NotifyDriverMbx_Module__loggerObj__C_offset)))
#else
#define Module__LOGOBJ ti_sdo_ipc_family_vayu_NotifyDriverMbx_Module__loggerObj__C
#endif

#undef Module__LOGFXN0
#ifdef ti_sdo_ipc_family_vayu_NotifyDriverMbx_Module__loggerFxn0__CR
#define Module__LOGFXN0 (*((CT__ti_sdo_ipc_family_vayu_NotifyDriverMbx_Module__loggerFxn0 *)(xdcRomConstPtr + ti_sdo_ipc_family_vayu_NotifyDriverMbx_Module__loggerFxn0__C_offset)))
#else
#define Module__LOGFXN0 ti_sdo_ipc_family_vayu_NotifyDriverMbx_Module__loggerFxn0__C
#endif

#undef Module__LOGFXN1
#ifdef ti_sdo_ipc_family_vayu_NotifyDriverMbx_Module__loggerFxn1__CR
#define Module__LOGFXN1 (*((CT__ti_sdo_ipc_family_vayu_NotifyDriverMbx_Module__loggerFxn1 *)(xdcRomConstPtr + ti_sdo_ipc_family_vayu_NotifyDriverMbx_Module__loggerFxn1__C_offset)))
#else
#define Module__LOGFXN1 ti_sdo_ipc_family_vayu_NotifyDriverMbx_Module__loggerFxn1__C
#endif

#undef Module__LOGFXN2
#ifdef ti_sdo_ipc_family_vayu_NotifyDriverMbx_Module__loggerFxn2__CR
#define Module__LOGFXN2 (*((CT__ti_sdo_ipc_family_vayu_NotifyDriverMbx_Module__loggerFxn2 *)(xdcRomConstPtr + ti_sdo_ipc_family_vayu_NotifyDriverMbx_Module__loggerFxn2__C_offset)))
#else
#define Module__LOGFXN2 ti_sdo_ipc_family_vayu_NotifyDriverMbx_Module__loggerFxn2__C
#endif

#undef Module__LOGFXN4
#ifdef ti_sdo_ipc_family_vayu_NotifyDriverMbx_Module__loggerFxn4__CR
#define Module__LOGFXN4 (*((CT__ti_sdo_ipc_family_vayu_NotifyDriverMbx_Module__loggerFxn4 *)(xdcRomConstPtr + ti_sdo_ipc_family_vayu_NotifyDriverMbx_Module__loggerFxn4__C_offset)))
#else
#define Module__LOGFXN4 ti_sdo_ipc_family_vayu_NotifyDriverMbx_Module__loggerFxn4__C
#endif

#undef Module__LOGFXN8
#ifdef ti_sdo_ipc_family_vayu_NotifyDriverMbx_Module__loggerFxn8__CR
#define Module__LOGFXN8 (*((CT__ti_sdo_ipc_family_vayu_NotifyDriverMbx_Module__loggerFxn8 *)(xdcRomConstPtr + ti_sdo_ipc_family_vayu_NotifyDriverMbx_Module__loggerFxn8__C_offset)))
#else
#define Module__LOGFXN8 ti_sdo_ipc_family_vayu_NotifyDriverMbx_Module__loggerFxn8__C
#endif

#undef Module__G_OBJ
#ifdef ti_sdo_ipc_family_vayu_NotifyDriverMbx_Module__gateObj__CR
#define Module__G_OBJ (*((CT__ti_sdo_ipc_family_vayu_NotifyDriverMbx_Module__gateObj *)(xdcRomConstPtr + ti_sdo_ipc_family_vayu_NotifyDriverMbx_Module__gateObj__C_offset)))
#else
#define Module__G_OBJ ti_sdo_ipc_family_vayu_NotifyDriverMbx_Module__gateObj__C
#endif

#undef Module__G_PRMS
#ifdef ti_sdo_ipc_family_vayu_NotifyDriverMbx_Module__gatePrms__CR
#define Module__G_PRMS (*((CT__ti_sdo_ipc_family_vayu_NotifyDriverMbx_Module__gatePrms *)(xdcRomConstPtr + ti_sdo_ipc_family_vayu_NotifyDriverMbx_Module__gatePrms__C_offset)))
#else
#define Module__G_PRMS ti_sdo_ipc_family_vayu_NotifyDriverMbx_Module__gatePrms__C
#endif

#undef Module__GP_create
#define Module__GP_create ti_sdo_ipc_family_vayu_NotifyDriverMbx_Module_GateProxy_create
#undef Module__GP_delete
#define Module__GP_delete ti_sdo_ipc_family_vayu_NotifyDriverMbx_Module_GateProxy_delete
#undef Module__GP_enter
#define Module__GP_enter ti_sdo_ipc_family_vayu_NotifyDriverMbx_Module_GateProxy_enter
#undef Module__GP_leave
#define Module__GP_leave ti_sdo_ipc_family_vayu_NotifyDriverMbx_Module_GateProxy_leave
#undef Module__GP_query
#define Module__GP_query ti_sdo_ipc_family_vayu_NotifyDriverMbx_Module_GateProxy_query

/* Object__sizingError */
#line 1 "Error_inconsistent_object_size_in_ti.sdo.ipc.family.vayu.NotifyDriverMbx"
typedef char ti_sdo_ipc_family_vayu_NotifyDriverMbx_Object__sizingError[sizeof(ti_sdo_ipc_family_vayu_NotifyDriverMbx_Object) > sizeof(ti_sdo_ipc_family_vayu_NotifyDriverMbx_Struct) ? -1 : 1];


#endif /* ti_sdo_ipc_family_vayu_NotifyDriverMbx__INTERNAL____ */
