-include ../../Rules.make

ENV_SETUP ?= ../../linux-devkit/environment-setup
DESTDIR ?= 
MATRIX_APP_DIR ?= /usr/share/matrix-gui-2.0/apps/

all: release

.PHONY: qmake
qmake: video_graphics_test.pro
	@. ${ENV_SETUP}; \
	qmake CONFIG+=release video_graphics_test.pro

qmake_debug : video_graphics_test.pro
	@. ${ENV_SETUP}; \
	qmake CONFIG+=debug video_graphics_test.pro

debug : qmake_debug
	@. ${ENV_SETUP}; \
	make

release : qmake
	@. ${ENV_SETUP}; \
	make

clean : qmake
	@. ${ENV_SETUP}; \
	make distclean

install_common:
	@if [ ! -d $(DESTDIR) ] ; then \
		echo "The extracted target filesystem directory doesn't exist."; \
		echo "Please run setup.sh in the SDK's root directory and then try again."; \
		exit 1; \
	fi
	@install -d ${DESTDIR}/usr/bin
	@install video_graphics_test ${DESTDIR}/usr/bin/video_graphics_test

install: release install_common
	@echo "video_graphics_test release version installed."

install_debug: debug install_common
	@echo "vidoe_graphics_test debug version installed."

