-include ../../Rules.make

ENV_SETUP ?= ../../../linux-devkit/environment-setup
DESTDIR ?= 

all: release

.PHONY: qmake
qmake : digiflip.pro
	@. ${ENV_SETUP}; \
	qmake CONFIG+=release digiflip.pro

release : qmake
	@. ${ENV_SETUP}; \
	make

clean : qmake
	@. ${ENV_SETUP}; \
	make distclean
