#!/bin/sh
# Begin section update-alternatives
update-alternatives --remove  passwd /home/robe/ti-processor-sdk-linux-am57xx-evm-04.03.00.05/linux-devkit/sysroots/x86_64-arago-linux/usr/bin/passwd.shadow
update-alternatives --remove  chfn /home/robe/ti-processor-sdk-linux-am57xx-evm-04.03.00.05/linux-devkit/sysroots/x86_64-arago-linux/usr/bin/chfn.shadow
update-alternatives --remove  chsh /home/robe/ti-processor-sdk-linux-am57xx-evm-04.03.00.05/linux-devkit/sysroots/x86_64-arago-linux/usr/bin/chsh.shadow
update-alternatives --remove  chpasswd /home/robe/ti-processor-sdk-linux-am57xx-evm-04.03.00.05/linux-devkit/sysroots/x86_64-arago-linux/usr/bin/chpasswd.shadow
update-alternatives --remove  vipw /home/robe/ti-processor-sdk-linux-am57xx-evm-04.03.00.05/linux-devkit/sysroots/x86_64-arago-linux/sbin/vipw.shadow
update-alternatives --remove  vigr /home/robe/ti-processor-sdk-linux-am57xx-evm-04.03.00.05/linux-devkit/sysroots/x86_64-arago-linux/sbin/vigr.shadow
# End section update-alternatives
